licenses(['notice'])

package(default_visibility = ['//visibility:public'])

cc_library(
    name = 'liblua_headers',
    hdrs = [
        'lauxlib.h',
        'lua.h',
        'luaconf.h',
        'lualib.h',
    ],
    includes = ['.'],
)

cc_library(
    name = 'liblua',
    srcs = [
        'lapi.c',
        'lapi.h',
        'lauxlib.c',
        'lauxlib.h',
        'lbaselib.c',
        'lbitlib.c',
        'lcode.c',
        'lcode.h',
        'lcorolib.c',
        'lctype.c',
        'lctype.h',
        'ldblib.c',
        'ldebug.c',
        'ldebug.h',
        'ldo.c',
        'ldo.h',
        'ldump.c',
        'lfunc.c',
        'lfunc.h',
        'lgc.c',
        'lgc.h',
        'linit.c',
        'liolib.c',
        'llex.c',
        'llex.h',
        'llimits.h',
        'lmathlib.c',
        'lmem.c',
        'lmem.h',
        'loadlib.c',
        'lobject.c',
        'lobject.h',
        'lopcodes.c',
        'lopcodes.h',
        'loslib.c',
        'lparser.c',
        'lparser.h',
        'lstate.c',
        'lstate.h',
        'lstring.c',
        'lstring.h',
        'lstrlib.c',
        'ltable.c',
        'ltable.h',
        'ltablib.c',
        'ltm.c',
        'ltm.h',
        'lundump.c',
        'lundump.h',
        'lutf8lib.c',
        'lvm.c',
        'lvm.h',
        'lzio.c',
        'lzio.h',
    ],
    hdrs = [
        'lauxlib.h',
        'lua.h',
        'lprefix.h',
        'luaconf.h',
        'lualib.h',
    ],
    includes = ['.'],
    linkopts = ['-ldl'],
)

cc_binary(
    name = 'lua',
    srcs = ['lua.c'],
    deps = [':liblua'],
)
